sudo: required
services:
  - docker

before_install:
  - docker build -t jabdi/docker-react-frontend -f Dockerfile.dev .
  
script:
  - docker run -e CI=true jabdi/docker-react-frontend npm run test

deploy: 
  provider: elasticbeanstalk
  region: us-west-1
  app: frontend
  env: Frontend-env
  bucket_name: elasticbeanstalk-us-west-1-124355643802
  bucket_path: frontend
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  version: 1.0.0