name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Build Docker image from Dockerfile.dev
        run: docker build -f Dockerfile.dev -t my-app-dev .
      - name: Run tests in Docker container
        run: docker run -e CI=true my-app-dev npm run test
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: |
          zip deploy.zip Dockerfile
          pip install awsebcli
          eb use Frontend-env
          eb deploy --staged